spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: khagesh
    password: khagesh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: ALWAYS
  data:
    redis:
      host: redis-service
      port: 6379
  cache:
    type: redis

server:
  port: 4000

grpc:
  server:
    port: 9002

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,cache
  endpoint:
    prometheus:
      access: UNRESTRICTED
  prometheus:
    metrics:
      export:
        enabled: true
