spring:
  application:
    name: APIGateway
  data:
    redis:
      host: redis-service
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.replenishRate: 10
                key-Resolver: "#{@ipAddressKeyResolver}"
          routes:
            - id: product-service-route
              uri: http://product-service:4000
              predicates:
                - Path=/auth/products/**
              filters:
                - StripPrefix=1
                - JwtFilter

            - id: order-service
              uri: http://order-service:9800
              predicates:
                - Path=/auth/api/orders/**
              filters:
                - StripPrefix=1
                - JwtFilter

            - id: auth-service-route
              uri: http://auth-service:8000
              predicates:
                - Path=/auth/**

server:
  port: 8080

logging:
  level:
    root: info

service:
  url: http://auth-service:8000