global:
  scrape_interval: 5s

scrape_configs:
  -   job_name: 'product-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['product-service.ecommerce.local:4000']