spring:
  application:
    name: OrderService
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

kafka:
  topics:
    order-created: order-created
    order-confirmed: order-confirmed
    order-failed: order-failed
    payment-completed: payment-completed
    payment-creation-failed: payment-creation-failed

payment:
  server:
    address: payment-service
    port: 9001


product:
  grpc:
    server: product-service
    port: 9002

server:
  port: 9800

resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsHalfInOpenState: 3
        automaticTransitionFromOpentoHalfOpenEnabled: true

  retry:
    instances:
      paymentServiceCircuitBreakerRetry:
        maxAttempts: 2
        waitDuration: 500ms



