name: CI-CD workflow to build,test and publish docker images

on: [push,pull_request,workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: pull the code from github
        uses: actions/checkout@v4

      - name: install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: build the APIGateway JAR
        run: |
          cd ./APIGateway/
          mvn clean package -DskipTests

      - name: build the AuthService JAR
        run: |
          cd ./AuthService/
          mvn clean package -DskipTests

      - name: build the OrderService JAR
        run: |
          cd ./OrderService/
          mvn clean package -DskipTests

      - name: build the PaymentService JAR
        run: |
          cd ./PaymentService/
          mvn clean package -DskipTests

      - name: build the ProductService JAR
        run: |
          cd ./ProductService/
          mvn clean package -DskipTests

      - name: start all the services
        run: docker compose up -d && sleep 120

      - name: Run all the Integration tests
        run: |
          cd ./Integration\ Tests/
          mvn clean verify

      - name: get logs in case of failure
        if: ${{ failure() }}
        run: docker compose logs

      - name: stop all services
        if: ${{ always() }}
        run: docker compose down -v

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: pull the code from repo
        uses: actions/checkout@v4

      - name: Login to Github Container Repository
        run: echo "${{secrets.GITHUB_TOKEN}}"| docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: Build the docker images for Github Container Repo
        run: |
          docker build -t ghcr.io/${{github.repository_owner}}/api-gateway:latest ./APIGateway/
          docker build -t ghcr.io/${{github.repository_owner}}/auth-service:latest ./AuthService/
          docker build -t ghcr.io/${{github.repository_owner}}/order-service:latest ./OrderService/
          docker build -t ghcr.io/${{github.repository_owner}}/payment-service:latest ./PaymentService/
          docker build -t ghcr.io/${{github.repository_owner}}/product-service:latest ./ProductService/

      - name: Use the Same Image but change tag for Docker Hub publishing
        run: |
          docker tag ghcr.io/${{github.repository_owner}}/api-gateway:latest ${{secrets.DOCKER_USER}}/the-ecomm-app:api-gateway
          docker tag ghcr.io/${{github.repository_owner}}/auth-service:latest ${{secrets.DOCKER_USER}}/the-ecomm-app:auth-service
          docker tag ghcr.io/${{github.repository_owner}}/order-service:latest ${{secrets.DOCKER_USER}}/the-ecomm-app:order-service
          docker tag ghcr.io/${{github.repository_owner}}/payment-service:latest ${{secrets.DOCKER_USER}}/the-ecomm-app:payment-service
          docker tag ghcr.io/${{github.repository_owner}}/product-service:latest ${{secrets.DOCKER_USER}}/the-ecomm-app:product-service

      - name: Push to Github Container Repo
        run: |
          docker push ghcr.io/${{github.repository_owner}}/api-gateway:latest
          docker push ghcr.io/${{github.repository_owner}}/auth-service:latest
          docker push ghcr.io/${{github.repository_owner}}/order-service:latest
          docker push ghcr.io/${{github.repository_owner}}/payment-service:latest
          docker push ghcr.io/${{github.repository_owner}}/product-service:latest

      - name: Push to the private Docker Hub
        run: |
          docker push ${{secrets.DOCKER_USER}}/the-ecomm-app:api-gateway
          docker push ${{secrets.DOCKER_USER}}/the-ecomm-app:auth-service
          docker push ${{secrets.DOCKER_USER}}/the-ecomm-app:order-service
          docker push ${{secrets.DOCKER_USER}}/the-ecomm-app:payment-service
          docker push ${{secrets.DOCKER_USER}}/the-ecomm-app:product-service
          
          
